/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_8_jacektracz_tutorial;

import org.junit.jupiter.api.Test;

import com.jacektracz.java8.starter.Library;

public class LibraryTest {
	@Test public void gg() {

	}
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
